DROP TABLE IF EXISTS a_user;
DROP TABLE IF EXISTS post;

CREATE TABLE a_user (
  id SERIAL PRIMARY KEY ,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
 /*user is reserve word*/
CREATE TABLE post (
  id SERIAL PRIMARY KEY ,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES a_user (id)
);